server:
  session-timeout: 1800
  port: 9999
security:
  basic:
    enabled: false
spring:
  application:
    name: shop-huizhi
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: res
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true

